### PR TITLE
Make extra-deps in stack.yaml optional

### LINKED ISSUE #28: Error parsing stack.yaml file
I installed stack2nix 0.1.3.0:

```
nix-env -f https://github.com/NixOS/nixpkgs/tarball/8de4530b4acfcda703cac98448120aa837043983 -iA haskellPackages.stack2nix
```

I wanted to try it on some random project: https://github.com/haskell-servant/example-servant-persistent

stack.yaml:
```
resolver: lts-6.2
packages:
  - '.'
```

This fails with the following output:

```
Ensuring cabal2nix version is >= 2.2.1 ...
Ensuring git version is >= 2 ...
Ensuring cabal version is >= 1 ...
stack2nix: Failed to parse ./stack.yaml
CallStack (from HasCallStack):
  error, called at src/Stack2nix.hs:158:24 in stack2nix-0.1.3.0-L6x2s4dmjRmKw75ThmpeHH:Stack2nix

```

----

Sorry if this might be something obvious. I really don't know much about stack and its config files at all.

### PR DESCRIPTION
**Pull request by gilligan**
This seems to fix #28

### CODE REVIEW

**Comment by domenkozar** [comment]
@gilligan need to fix also usages :)

**Comment by gilligan** [comment]
Sorry, should have actually tried it with some yaml with extra deps.. 😜
Or even better lets start adding some tests for this :)

**Comment by domenkozar** [comment]
Yeah there should be a minimal functional test (I remember @jmitchell wrote some already), but I don't know the status of that.

**Comment by domenkozar** [comment]
Superseeded by https://github.com/input-output-hk/stack2nix/pull/42

**Pull request closed without merging**
