### PR TITLE
Add flag to clone a git repository `recursive`

### PR DESCRIPTION
**Pull request by sectore**
to support `git` submodules.

I came across that issue while trying to update https://github.com/domenkozar/hie-nix to latest [`HIE`](https://github.com/haskell/haskell-ide-engine). Because `HIE` is [using submodules now](https://github.com/haskell/haskell-ide-engine/pull/526), `stack2nix` was thrown an error about missing sources of submodules defined in [`stack-8.2.1.yaml`](https://github.com/haskell/haskell-ide-engine/blob/master/stack-8.0.2.yaml) or  [`stack-8.2.1.yaml`](https://github.com/haskell/haskell-ide-engine/blob/master/stack-8.0.2.yaml).

This PR will fix that issue.

### CODE REVIEW

**Comment by domenkozar** [comment]
@jmitchell do you think we could merge this?

**Comment by domenkozar** [comment]
Actually, I think there's a problem. We are first cloning git repository with submodules for master HEAD, then we checkout to another branch. But if another branch has different submodules, this will fail. 

@sectore can you make submodule usage explicit command after checkout has been done?

**Comment by domenkozar** [comment]
Yes - `git submodule update --init --recursive`

**Comment by sectore** [comment]
@domenkozar Would `git clone --recurse-submodules {GIT-REPO} {DIR}` work as well? 

>  This is equivalent to running git submodule update --init --recursive <pathspec> immediately after the clone is finished. 

(^ https://git-scm.com/docs/git-clone#git-clone---recurse-submodulesltpathspec)

**Comment by sectore** [comment]
@domenkozar Or did you mean to run that `git submodule ...` command right after running `git checkout` https://github.com/sectore/stack2nix/blob/f95772fc762c5a0d9e3caded6ca5b98711fb85ad/src/Stack2nix/External/VCS/Git.hs#L38 ? I guess the latter, right?

**Comment by sectore** [comment]
@jmitchell _Friendly ping:_ Are you happy with that PR ^ or do you miss something? It would be great to have that PR in `master`... Thanks!

**Comment by domenkozar** [comment]
There is some kind of a bug that causes https://github.com/domenkozar/hie-nix/issues/13#issuecomment-395414400 - I will investigate tomorrow.

**Comment by puffnfresh** [comment]
Should this just be the default behaviour?

**Comment by domenkozar** [comment]
OK there's no bug in particular with this PR, but I've opened https://github.com/input-output-hk/stack2nix/issues/103

**Comment by jmitchell** [comment]
> Should this just be the default behaviour?

Unless there's some way we discover this could break other projects, that sounds good to me.

**Comment by domenkozar** [comment]
Mainly need to check if it has performance implications.

**Comment by domenkozar** [comment]
Couldn't find a reason not to do this, so I opened https://github.com/input-output-hk/stack2nix/pull/108

**Comment by domenkozar** [comment]
Thank you @sectore for this work!

**Pull request closed without merging**
