### PR TITLE
Remove bin-package-db

### PR DESCRIPTION
**Pull request by puffnfresh**
This allows generating plans using GHC 7.10 (e.g. Eta)

### CODE REVIEW

**Comment by puffnfresh** [comment]
Is this the best place to remove it from the plan?

**Comment by domenkozar** [comment]
This should be covered in https://github.com/input-output-hk/stack2nix/issues/84 I think

**Comment by domenkozar** [comment]
@puffnfresh for now best to add it into `src/Stack2nix/Render.hs:basePackages`

**Comment by puffnfresh** [comment]
Can I get this merged or similar functionality? I've been rebasing this change on top of master to be able to regenerate Eta's expressions.

**Comment by domenkozar** [comment]
Sorry about that, I've been a bit hesitant to merge this as it's not the right fix, but I understand it fixes your problem :)

A better way would be to move the filtering that is now in `Render.hs` into `Stack.hs` so it happens before package generation - which should also spare some cycles.

Would you like to merge this and open a clean up issue or address it properly now?

**Comment by puffnfresh** [comment]
What's not right about this fix? I haven't touched `Render.hs`.

**Comment by puffnfresh** [comment]
@domenkozar I'm happy to do more work on this but I'm just not sure where.

**Comment by domenkozar** [comment]
@puffnfresh no worries, the code is a mess anyway. I'll return to #84 hopefully soon and also address my concern with your fix.

**Pull request merged**
