### PR TITLE
Fixes for #117 and #119

### LINKED ISSUE #117: Failure to recognise the license in stack new simple-library template.
A new stack project created from template using the simple-library template fails conversion with `stack2nix`.

To reproduce this, create a new stack project using the simple-library template. Run `stack2nix` on this as a local path. The license is described as `BSD3` in `package.yaml` and there is a `LICENSE` file but the conversion stops and reports an error of;

    unknown licenseUnknownLicense "BSD3ClauseORApache20"

I have a repository with [this test case](https://github.com/philderbeast/stack2nix-test-cases/tree/master/simple-library).

```
> stack new simple-library
Downloading template "new-template" to create project "simple-library" in simple-library/ ...

The following parameters were needed by the template but not provided: author-email, author-name, category, copyright, github-username
You can provide them in /Users/pdejoux/.stack/config.yaml, like this:
templates:
  params:
    author-email: value
    author-name: value
    category: value
    copyright: value
    github-username: value
Or you can pass each one as parameters like this:
stack new simple-library new-template -p "author-email:value" -p "author-name:value" -p "category:value" -p "copyright:value" -p "github-username:value"

Looking for .cabal or package.yaml files to use to init the project.
Using cabal packages:
- simple-library/

Selecting the best among 14 snapshots...

* Matches lts-12.6

Selected resolver: lts-12.6
Initialising configuration using resolver: lts-12.6
Total number of user packages considered: 1
Writing configuration to file: simple-library/stack.yaml
All done.
```

```
> cd simple-library
simple-library> stack2nix --verbose . > default.nix
Ensuring git version is >= 2 ...
Ensuring cabal version is >= 2 ...
stack2nix (isLocalRepo): True
stack2nix (projRoot): "."
stack2nix (argUri): "."
handleStackConfig (cwd): /.../stack2nix-test-cases/simple-library
handleStackConfig (localDir): .
handleStackConfig (remoteUri): Nothing
handleStackConfig (alreadyExists): True
...
+ cabal2nix --subpath . --system x86_64-darwin cabal://ALUT-2.4.0.2
+ cabal2nix --subpath . --system x86_64-darwin cabal://Allure-0.8.3.0
...
+ cabal2nix --subpath . --system x86_64-darwin cabal://zot-0.0.3
+ cabal2nix --subpath . --system x86_64-darwin cabal://ztail-1.2.0.2
stack2nix: Distribution.Nixpkgs.Haskell.FromCabal.License.fromCabalLicense: unknown licenseUnknownLicense "BSD3ClauseORApache20"
Choose one of: GPL, GPL-2, GPL-3, LGPL, LGPL-2.1, LGPL-3, AGPL, AGPL-3, BSD2, BSD3, MIT, ISC, MPL-2.0, Apache, Apache-2.0, PublicDomain, AllRightsReserved, OtherLicense
CallStack (from HasCallStack):
  error, called at src/Distribution/Nixpkgs/Haskell/FromCabal/License.hs:39:62 in cabal2nix-2.10.2-46haP2jmk03DpwNz2ajA5I:Distribution.Nixpkgs.Haskell.FromCabal.License
```

```
> stack2nix --version
stack2nix 0.2
> cabal2nix --version
cabal2nix 2.10.2
> cabal --version
cabal-install version 2.2.0.0
compiled using version 2.2.0.0 of the Cabal library
> stack --version
Version 1.7.1, Git revision 681c800873816c022739ca7ed14755e85a579565 (5807 commits) x86_64 hpack-0.28.2
```

### PR DESCRIPTION
**Pull request by nh2**
See #117 and #119.

As of writing, my build to test it fixes #117 is still running.

### CODE REVIEW

**Comment by nh2** [comment]
> As of writing, my build to test it fixes #117 is still running.

Build failed, so I'll split this. Please merge #121 first.

**Comment by nh2** [comment]
> Build failed, so I'll split this

Now it should be good.

And I've tested that it fixes https://github.com/input-output-hk/stack2nix/issues/117#issuecomment-415895155 for me.

**Comment by nh2** [comment]
Rebased.

Last build travis complained that there was no `cabal2nix-2.11 in the database, did you run cabal update`? Odd.

**Comment by domenkozar** [comment]
You need to bump timestamp in stack2nix updating script.

**Comment by Infinisil** [comment]
Ping? I need the fix for #117

**Comment by domenkozar** [comment]
You also need to commit the new stack2nix output :)

**Comment by domenkozar** [comment]
Pushed to master, thanks.

**Pull request closed without merging**
